server.port=8085

# H2 Embedded Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Timezone configuration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# HikariCP configuration to disable autoCommit
spring.datasource.hikari.auto-commit=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cashfree Payment Gateway Configuration
cashfree.api.url=https://api.cashfree.com/pg
cashfree.app.id=TEST10945021166bff565c92da5f192d12054901
cashfree.secret.key=cfsk_ma_test_c7f4402b544346ebb2506f88cf0db1d4_560e4a99
cashfree.webhook.url=https://api.rajyadu.in/api/payments/webhook

# Logistics API Configuration
logistic.api.url=https://api.logistic.com
logistic.api.key=your_logistic_api_key
logistic.api.secret=your_logistic_api_secret

app.upload.dir=uploads

# SMS Configuration
sms.api.url=https://mdssend.in/api.php
sms.api.username=dhudaramsonsorganic
sms.api.key=GwVIxD9vknhy
sms.api.senderid=MOBTIN
sms.api.route=OTP

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
